language: java
jdk:
  - openjdk8

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SHOULD_BE_GENERATED_BY_TRAVIC_CLI
  file: build/libs/nerd-golf-tracker.jar
  on:
    repo: golfholger/nerd-golf-tracker
    tags: true
